#!/bin/bash
# Installs XcodeGen of one release for the workflows: the project CI builds is generated by the
# same XcodeGen every day, not by whatever the runner's Homebrew formula says that morning
# (`brew install xcodegen` gave 2.46.0 on 21.09, and nothing held it there). Built from the
# tagged source, which is checked against its checksum before a byte of it is compiled; the
# checksum is the one Homebrew's own formula of this release carries. The layout is Homebrew's
# too: `<prefix>/bin/xcodegen` finds its presets in `<prefix>/share/xcodegen/SettingPresets`.
#
# Moving to another release: change `version` and `checksum` together, with the checksum from
# `brew info --json=v2 xcodegen` (`urls.stable.checksum`) or from a download checked by hand.
# The owner's Mac is told when its own xcodegen is another release (`make generate`).
#
# Usage: install-xcodegen.sh <prefix>   builds and installs there; on a runner, puts
#                                       <prefix>/bin on the PATH of the steps after it
#        install-xcodegen.sh --pinned   prints the release this repository is pinned to
#        install-xcodegen.sh --self-test
set -euo pipefail

version="2.46.0"
checksum="c83c7bd70255b0ddf4116dadce16bdf0e5939165b43a544e124de294ec84aa27"
source_url="https://github.com/yonaskolb/XcodeGen/archive/refs/tags/${version}.tar.gz"

fail() { printf 'install-xcodegen: %s\n' "$1" >&2; exit 1; }

# Whether the file has this SHA-256.
verified() {
  local sum
  sum="$(shasum -a 256 "$1" | awk '{ print $1 }')"
  [ "${sum}" = "$2" ]
}

# The release an xcodegen says it is: `Version: 2.46.0` → 2.46.0.
said_version() {
  "$1" --version 2> /dev/null | sed -n 's/^Version: *//p' | sed -n 1p
}

if [ "${1:-}" = "--self-test" ]; then
  scratch="$(mktemp -d "${TMPDIR:-/tmp}/itogo-xcodegen.XXXXXX")"
  trap 'rm -rf "${scratch}"' EXIT
  printf 'a release\n' > "${scratch}/source.tar.gz"
  sum="$(shasum -a 256 "${scratch}/source.tar.gz" | awk '{ print $1 }')"
  verified "${scratch}/source.tar.gz" "${sum}" ||
    { echo "install-xcodegen self-test: refused a file with its own checksum"; exit 1; }
  if verified "${scratch}/source.tar.gz" "${checksum}"; then
    echo "install-xcodegen self-test: took a file for the one the checksum names"
    exit 1
  fi
  for said in "${version}" 2.47.0; do
    printf '#!/bin/bash\necho "Version: %s"\n' "${said}" > "${scratch}/xcodegen-${said}"
    chmod +x "${scratch}/xcodegen-${said}"
  done
  [ "$(said_version "${scratch}/xcodegen-${version}")" = "${version}" ] ||
    { echo "install-xcodegen self-test: did not read the version of an xcodegen"; exit 1; }
  [ "$(said_version "${scratch}/xcodegen-2.47.0")" != "${version}" ] ||
    { echo "install-xcodegen self-test: took 2.47.0 for ${version}"; exit 1; }
  [[ "${checksum}" =~ ^[0-9a-f]{64}$ ]] ||
    { echo "install-xcodegen self-test: the pinned checksum is not a SHA-256"; exit 1; }
  echo "install-xcodegen self-test: ok"
  exit 0
fi

if [ "${1:-}" = "--pinned" ]; then
  printf '%s\n' "${version}"
  exit 0
fi

[ "$#" -eq 1 ] || fail "usage: install-xcodegen.sh <prefix> | --pinned | --self-test"
prefix="$1"
work="$(mktemp -d "${TMPDIR:-/tmp}/xcodegen-build.XXXXXX")"
trap 'rm -rf "${work}"' EXIT

curl -fsSL --retry 3 -o "${work}/source.tar.gz" "${source_url}" ||
  fail "could not download ${source_url}"
verified "${work}/source.tar.gz" "${checksum}" ||
  fail "the source of XcodeGen ${version} does not have the checksum this script pins; nothing was built"
tar -xzf "${work}/source.tar.gz" -C "${work}"
src="${work}/XcodeGen-${version}"
[ -d "${src}" ] || fail "the archive holds no XcodeGen-${version}"

# SwiftPM takes the dependencies within the ranges of the release's own Package.swift, at the
# revisions of its Package.resolved where the release ships one.
swift build --package-path "${src}" -c release --disable-sandbox
mkdir -p "${prefix}/bin" "${prefix}/share/xcodegen"
cp "$(swift build --package-path "${src}" -c release --show-bin-path)/xcodegen" "${prefix}/bin/xcodegen"
rm -rf "${prefix}/share/xcodegen/SettingPresets"
cp -R "${src}/SettingPresets" "${prefix}/share/xcodegen/SettingPresets"

said="$(said_version "${prefix}/bin/xcodegen")"
[ "${said}" = "${version}" ] || fail "the xcodegen built says «${said}», not ${version}"
if [ -n "${GITHUB_PATH:-}" ]; then
  printf '%s\n' "${prefix}/bin" >> "${GITHUB_PATH}"
fi
printf 'install-xcodegen: XcodeGen %s in %s\n' "${version}" "${prefix}/bin"
